### ISSUE TITLE
Login failed after sleeping

### ISSUE THREAD

**Issue by Dimitrius1** [glad-tidings/BumsBot#10]
On startup everything works fine, but after sleeping, a login error is present.

[Bums] [1] synced successfully. 
.......................................
[Blum] [1] sync sleep '1h 13m 16s'
[Bums] [1] login failed
[Blum] [1] sync sleep '1h 15m 49s'
[Bums] [1] login failed
[Blum] [1] sync sleep '1h 12m 31s'
.......................................

**Comment by glad-tidings** [comment]
use new version
