### ISSUE TITLE
Synced failed on startup

### ISSUE THREAD

**Issue by Dimitrius1** [glad-tidings/BumsBot#12]
[Bums] [1] my ip 'x.x.x.x'
[Bums] [1] login successfully.
[Bums] [1] synced failed
........
Creating a new session does not help

**Comment by glad-tidings** [comment]
Are you using v2.2?

**Comment by Imaroubat** [comment]
> [Bums] [1] my ip 'x.x.x.x' [Bums] [1] login successfully. [Bums] [1] synced failed ........ Creating a new session does not help

i have this problem too, using last version. it worked before you add session self making features

**Comment by Dimitrius1** [comment]
> Are you using v2.2?

yes, last version. 

With "seedbot" almost the same problem, but the error is a bit different. These errors appeared after adding sessions.  
[Seed] [1] get profile data failed
[Seed] [1] sync sleep '4h 45m 8s'

**Comment by glad-tidings** [comment]
fix sync failed problem
