### ISSUE TITLE
add query

### ISSUE THREAD

**Issue by gamang** [glad-tidings/BumsBot#14]
can you please add run using query please

**Comment by glad-tidings** [comment]
query expire in 2 days in bums

**Comment by gamang** [comment]
its oke , i will fill it every 2days , and need to support multi account

**Comment by glad-tidings** [comment]
https://github.com/glad-tidings/BumsBot/releases/tag/v2.4

download BumsBotQuery

**Comment by gamang** [comment]
cant download can you add new repository for it ?

**Comment by glad-tidings** [comment]
https://github.com/glad-tidings/BumsBotQuery
