### ISSUE TITLE
Error after reaching level 9

### ISSUE THREAD

**Issue by Dimitrius1** [glad-tidings/BumsBot#15]
Error after reaching level 9:
[Bums] [1] my ip 'x.x.x.x'
[Bums] [1] login successfully.
[Bums] [1] Error: The JSON value could not be converted to System.String. Path: $.data.gameInfo.todayMaxCollegeCoin | LineNumber: 0 | BytePositionInLine: 884.
Thx.

**Comment by glad-tidings** [comment]
fix this issue, use new version

**Comment by Dimitrius1** [comment]
> fix this issue, use new version

Version 2.5, error:

[2024-12-15 22:35:55] [Bums] [...] Error: The JSON value could not be converted to System.Int32. Path: $.data.gameInfo.todayMaxCollegeCoin | LineNumber: 0 | BytePositionInLine: 884.

Another account where level 8 is all good, where 9 is there is an error.

**Comment by glad-tidings** [comment]
Please use v2.6 and tell me the result

**Comment by Dimitrius1** [comment]
> Please use v2.6 and tell me the result

Now it's work. Thx.
