### ISSUE TITLE
 synced failed

### ISSUE THREAD

**Issue by Imaroubat** [glad-tidings/BumsBot#2]
how to solve "synced failed"?

**Comment by glad-tidings** [comment]
Did you add query_id to data.txt?

**Comment by Imaroubat** [comment]
> Did you add query_id to data.txt?

Why write a bot using `query_id` if the data expires in two days and the bot stops working? Pulling `query_id` for farm every other day is quite a hassle.

**Comment by AntiWarforever** [comment]
> > Did you add query_id to data.txt?
> 
> Why write a bot using `query_id` if the data expires in two days and the bot stops working? Pulling `query_id` for farm every other day is quite a hassle.

yes but i don't know why all js developers use just query but python developers use session (This means that all of them are so unemployed that they get queries for several accounts every day)
Whenever we ask them how to solve the query problem, they don't give any answer

**Comment by glad-tidings** [comment]
https://github.com/glad-tidings/TelegramMiniAppQueryID
